/* CREACION DE TABLAS */

CREATE TABLE Desarrollador(
	ID_DESARROLLADOR smallint GENERATED ALWAYS AS IDENTITY,
	nombres varchar(35) NOT NULL,
    apellidos varchar(35) NOT NULL,
    alias varchar(20) NOT NULL UNIQUE,
	estado boolean NOT NULL DEFAULT true,
	PRIMARY KEY(ID_DESARROLLADOR)
);

CREATE TABLE Aplicacion(
	ID_APLICACION integer GENERATED ALWAYS AS IDENTITY,
    FK_ID_CATEGORIA smallint,
	nombre varchar(40) NOT NULL,
    fecha_lanz date NOT NULL,
	estado boolean NOT NULL DEFAULT true,
	PRIMARY KEY(ID_APLICACION)
);

CREATE TABLE APLICACION_DESARROLLADOR(
	FK_ID_APLICACION integer,
	FK_ID_DESARROLLADOR smallint,
	fecha_reg date DEFAULT CURRENT_DATE,
	estado boolean NOT NULL DEFAULT true,
	PRIMARY KEY(FK_ID_APLICACION, FK_ID_DESARROLLADOR)
);

CREATE TABLE Categoria(
	ID_CATEGORIA smallint GENERATED ALWAYS AS IDENTITY,
	nombre varchar(25) NOT NULL UNIQUE,
	estado boolean NOT NULL DEFAULT true,
	PRIMARY KEY(ID_CATEGORIA)
);

/* LLAVES FORANES */

ALTER TABLE APLICACION_DESARROLLADOR 
	ADD CONSTRAINT fk_id_aplicacion_apl_des FOREIGN KEY (FK_ID_APLICACION) REFERENCES Aplicacion (ID_APLICACION),
	ADD CONSTRAINT fk_id_desarollador_apl_des FOREIGN KEY (FK_ID_DESARROLLADOR) REFERENCES Desarrollador (ID_DESARROLLADOR);

ALTER TABLE Aplicacion ADD CONSTRAINT fk_id_categoria_apl FOREIGN KEY (FK_ID_CATEGORIA) REFERENCES Categoria (ID_CATEGORIA);